spring:
  datasource:
    url: jdbc:mysql://localhost:3306/expense-manager?useSSL=false
    username: root
    password: 



  # The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


#JPA Settings
  jpa.hibernate.ddl_auto: create

management:
  endpoint:
    shutdown:
      enabled: true